apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: test
resources:
- ../../base
images:
- name: appv1
  newName: 214084917052.dkr.ecr.ap-northeast-1.amazonaws.com/app-test
  newTag: aa7c6c3a0ad96550085e059fee7dc526df5600cd