apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: test
resources:
- ../../base
images:
- name: appv1
  newName: 214084917052.dkr.ecr.ap-northeast-1.amazonaws.com/app-prod
  newTag: 1defbbe31c60639d7727ff9b0523207450749252
